export const HOST = 'localhost'
export const USER = 'root'
export const PASSWORD = ''
export const DATABASE = 'cmsai'
export const ADAPTER = 'mysql'
export const ALGORITHM = 'RS256'
export const EXPIRESIN = '12h'